export const QOBILAHS = [
  "QOBILAH MARIYAH", "QOBILAH BUSYRI", "QOBILAH MUZAMMAH", "QOBILAH SULHAN",
  "QOBILAH SHOLIHATUN", "QOBILAH NURSIYAM", "QOBILAH NI'MAH", "QOBILAH ABD MAJID",
  "QOBILAH SAIDAH", "QOBILAH THOHIR AL ALY", "NYAI NIHAYA (NGAGLIK)"
];
